image:
  repository: tccr.io/truecharts/tdarr_node
  pullPolicy: IfNotPresent
  tag: v2.00.24@sha256:1f04e1b47d983df5d6cc62ca233098b2743d84883514cc545475d705bcc5b812
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  configs:
    enabled: true
    mountPath: "/app/configs"
  logs:
    enabled: true
    mountPath: "/app/logs"
  transcode-cache:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"
  varrun:
    enabled: true
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            # User Defined
            nodeID: "myFirstTdarrNode"
            serverIP: "0.0.0.0"
            serverPort: 8266
