apiVersion: v2
appVersion: "1.1.3.2982"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.4.20
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 11.0.31
deprecated: false
description: Looks and smells like Sonarr but made for music
home: https://truecharts.org/charts/stable/lidarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lidarr.png
keywords:
  - lidarr
  - torrent
  - usenet
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: lidarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/lidarr
  - https://github.com/Lidarr/Lidarr
type: application
version: 15.0.6
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
