image:
  repository: tccr.io/truecharts/lidarr
  pullPolicy: IfNotPresent
  tag: 1.1.3.2982@sha256:0f635e1c21c6e6ef8a67f246b3e7f1ca3409f1f08bf8d2006abfaa89da55d534
service:
  main:
    ports:
      main:
        port: 8686
persistence:
  config:
    enabled: true
    mountPath: /config
cnpg:
  main:
    enabled: true

    database: lidarr
    user: lidarr
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              ## Set this to true if you wish to specify your own livenessProbe
              custom: true
              ## The spec field contains the values for the default livenessProbe.
              ## If you selected custom: true, this field holds the definition of the livenessProbe.
              spec:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - -c
                    - curl --fail localhost:8686/api/v1/system/status?apiKey=`IFS=\> && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
                failureThreshold: 5
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
          env:
            LIDARR__PORT: "{{ .Values.service.main.ports.main.port }}"
            LIDARR__AUTHENTICATION_METHOD: ""
            LIDARR__POSTGRES_PORT: 5432
            LIDARR__POSTGRES_USER: "{{ .Values.cnpg.main.user }}"
            LIDARR__POSTGRES_MAIN_DB: "{{ .Values.cnpg.main.database }}"
            LIDARR__POSTGRES_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            LIDARR__POSTGRES_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
