apiVersion: v2
appVersion: "4.3.2.6857"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.4.13
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 11.0.31
deprecated: false
description: "A fork of Sonarr to work with movies à la Couchpotato"
home: https://truecharts.org/charts/stable/radarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/radarr.png
keywords:
  - radarr
  - torrent
  - usenet
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: radarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/radarr
  - https://github.com/Radarr/Radarr
type: application
version: 15.0.4
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
