image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.4145@sha256:d597166cef918de21a867641961a156a34acecd75910ee73aa483fc5deccaa18
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/UI/Login"
            readiness:
              path: "/UI/Login"
            startup:
              path: "/UI/Login"
