image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.2814@sha256:530a77e88cadeaf1f924f08b18b33c9b11c17aa46702f5a5d40becf5dc38a30f
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/UI/Login"
            readiness:
              path: "/UI/Login"
            startup:
              path: "/UI/Login"
