image:
  repository: tccr.io/truecharts/radarr
  pullPolicy: IfNotPresent
  tag: 4.4.4.7068@sha256:93c49f0b56ef596a21217e3a5b4d8bb00ff68efc08325f1101d65c24e3c2684e
service:
  main:
    ports:
      main:
        port: 7878
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            readiness:
              enabled: true
              type: http
              path: /ping
            liveness:
              enabled: true
              type: http
              path: /ping
            startup:
              enabled: true
              type: http
              path: /ping

          env:
            RADARR__PORT: "{{ .Values.service.main.ports.main.port }}"
