image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.2814@sha256:2c81c6a545e656230ee0a275d1825435a1eb2e2c1568b7810a8f08ace5ce90a7
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/UI/Login"
            readiness:
              path: "/UI/Login"
            startup:
              path: "/UI/Login"
