image:
  repository: tccr.io/truecharts/mariadb
  pullPolicy: IfNotPresent
  tag: v10.11.4@sha256:c36949f30cb56ed38498d794a0a4fb34d58dcf6c45aa9107f292ab9f1df1c54c

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MARIADB_PASSWORD:
              secretKeyRef:
                expandObjectName: "{{ if .Values.mariadbPassword }}true{{ else }}false{{ end }}"
                name: '{{ if .Values.mariadbPassword }}credentials{{ else if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ printf "%s-%s" .Release.Name "mariadbcreds" }}{{ end }}'
                key: "mariadb-password"
            MARIADB_ROOT_PASSWORD:
              secretKeyRef:
                expandObjectName: "{{ if .Values.mariadbPassword }}true{{ else }}false{{ end }}"
                name: '{{ if .Values.mariadbPassword }}credentials{{ else if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ printf "%s-%s" .Release.Name "mariadbcreds" }}{{ end }}'
                key: "mariadb-root-password"
            MARIADB_USER: "{{ .Values.mariadbUsername }}"
            MARIADB_DATABASE: "{{ .Values.mariadbDatabase }}"
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - /bin/bash
                - -ec
                - "until /opt/bitnami/scripts/mariadb/healthcheck.sh; do sleep 2; done"
            readiness:
              enabled: true
              type: exec
              command:
                - /bin/bash
                - -ec
                - "until /opt/bitnami/scripts/mariadb/healthcheck.sh; do sleep 2; done"
            startup:
              enabled: true
              type: exec
              command:
                - /bin/bash
                - -ec
                - "until /opt/bitnami/scripts/mariadb/healthcheck.sh; do sleep 2; done"

service:
  main:
    ports:
      main:
        port: 3306
        targetPort: 3306

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0

secret:
  credentials:
    enabled: true
    data:
      mariadb-password: '{{ ( .Values.mariadbPassword | default "empty" ) }}'
      mariadb-root-password: '{{ ( .Values.mariadbRootPassword | default "empty" ) }}'

persistence:
  data:
    enabled: true
    mountPath: "/bitnami/mariadb"

mariadbUsername: "test"
mariadbDatabase: "test"
mariadbRootPassword: "testroot"

# -- Secret or password
# One of these options is required, unless used as a dependency for another TrueCharts chart.
mariadbPassword: ""
existingSecret: ""

portal:
  open:
    enabled: false

manifestManager:
  enabled: false
